### ISSUE TITLE
Use gulp-jspm

### ISSUE THREAD

**Issue by brillout** [alexweber/es6-jspm-gulp-boilerplate#13]
Instead of using a seperate NPM script for building jspm, https://github.com/brillout/gulp-jspm could be used instead

(I am the author of gulp-jspm)

**Comment by kmturley** [comment]
I've made a version using gulp-jspm. Thanks for creating the plugin, very useful :)
https://github.com/kmturley/es6-modules

**Comment by alexweber** [comment]
Open-source ftw! :+1:

**Comment by alexweber** [comment]
@kmturley I've circled back and decided to leverage your plugin since it adds value and helps with the build tasks running in the correct order.

Thanks for the great plugin! :+1:

**Comment by kmturley** [comment]
No problem, glad I could help! There are some useful things to note with gulp tasks:

1) Use return to tell gulp to wait for task to finish:

```
gulp.task('clean', function () {
    return del(['www']);
});
```

2) Use variables for your paths so they can be changed in one place:

```
global.paths = {
    css: '/**/*.css',
    html: '/**/*.html',
    img: '/**/*.{jpg,png}',
    js: '/**/*.js',
};
```

3) If you want a task to finish before another task, then it should be a dependancy e.g. the clean folder task:

**Should not be:**

```
gulp.task('optimise', ['clean', 'optimise.html',  'optimise.js']);
```

**Should be:**

```
gulp.task('optimise.html', ['clean'], function () {
    // do something
});

gulp.task('optimise.js', ['clean'], function () {
    // do something
});
```

**Comment by alexweber** [comment]
@kmturley Right on, thanks for sharing that!  In other projects what I've also done a lot of is use `execSync` for abstract build tasks when the order of execution of dependencies is critical.

To be honest, the build is super minimalistic, I should probably spruce it up a bit :)
