### ISSUE TITLE
gulp install does not work on fresh clone

### ISSUE THREAD

**Issue by ryanirilli** [alexweber/es6-jspm-gulp-boilerplate#9]
I have gulp installed globally, by running `gulp -v` I get `CLI version 3.9.0` but after cloning the repo I cannot run `gulp install` output is below

```
Local gulp not found in /my/project/path
Try running: npm install gulp
```

of course after I run `npm install` I can run the gulp install task, which successfully installs my jspm dependencies. Maybe update documentation to include this step?

**Comment by alexweber** [comment]
@ryanirilli Thanks for pointing that out!  I've removed that task and updated the documentation.
